name: "Update Platform Web"
run-name: Update ${{ github.event.client_payload.repo }} to ${{ github.event.client_payload.version }}
on:
  repository_dispatch:
    type: [web_new_version]
jobs:
  call-update-platform_web:
    if: ${{ github.event.client_payload.repo == 'ab_platform_web' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - branch: master
            webpack: update
          # - branch: develop
          #   webpack: dev
          #   pre_release: dev
    name: Update Service Web ${{ matrix.branch }} (Platform)
    uses: ./.github/workflows/update-build-release.yml
    secrets:
      TOKEN: ${{ secrets.PAT }}
    with: 
      version: ${{ github.event.client_payload.version }}
      type: ${{ github.event.client_payload.type }}
      pre_release: ${{ matrix.pre_release }}
      branch: ${{ matrix.branch }}
      webpack_repo: digi-serve/ab_platform_web
      webpack_repo_short: platform_web
      webpack_path: ab_platform_web
      webpack_command: ${{ matrix.webpack }}
  call-update-designer:
    if: ${{ github.event.client_payload.repo == 'plugin_ABDesigner' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - branch: master
            webpack: update
          # - branch: develop
          #   webpack: dev
          #   pre_release: dev
    name: Update Service Web ${{ matrix.branch }} (Designer)
    uses: ./.github/workflows/update-build-release.yml
    secrets:
      TOKEN: ${{ secrets.PAT }}
    with: 
      version: ${{ github.event.client_payload.version }}
      type: ${{ github.event.client_payload.type }}
      pre_release: ${{ matrix.pre_release }}
      branch: ${{ matrix.branch }}
      webpack_repo: digi-serve/plugin_ABDesigner
      webpack_repo_short: ABDesigner
      webpack_path: plugins/ABDesigner
      webpack_command: ${{ matrix.webpack }}
