name: Merging Rules
on:
   # Run on pull requests into the #master branch
   pull_request:
      branches: [master, develop]

jobs:
   call-e2e-tests:
      name: E2E Tests
      uses: digi-serve/.github/.github/workflows/cypress-e2e-tests.yml@master
